language: cpp
compiler: gcc
sudo: require
dist: xenial

script:
  - bash -ex build.sh
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
